# Generated by Django 4.2.8 on 2023-12-16 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiV1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee2',
            name='company',
        ),
    ]
