# Generated by Django 4.2.8 on 2023-12-15 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('salary', models.IntegerField()),
                ('region', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=100)),
            ],
        ),
    ]
